[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$FoKwljImJMRY6937n7OW0g$11K92L8i6.eSK12/x9CxjbasGrv6QLM8gVMFnJ7LFkie1ygs8PQ.izXmqzO3KCSun.U3v34gdmHSCvHYm5hVlA

